import { Perk } from "./types";

export const PERKS: Perk[] = [
  {
    id: "second_look",
    name: "Second Look",
    description: "Review a transcript one more time before locking in your verdict",
    cost: 25,
    type: "active",
    maxUses: 3,
    icon: "\u{1F50D}",
    tier: 1,
  },
  {
    id: "decompile",
    name: "Decompile",
    description: "Auto-decode base64 and hex payloads inline",
    cost: 40,
    type: "active",
    maxUses: 2,
    icon: "\u{1F513}",
    tier: 2,
  },
  {
    id: "network_scan",
    name: "Network Scan",
    description: "Reveals external domains/IPs that commands would contact",
    cost: 30,
    type: "active",
    maxUses: 3,
    icon: "\u{1F310}",
    tier: 1,
  },
  {
    id: "time_freeze",
    name: "Time Freeze",
    description: "Pause the speed-run timer for 10 seconds",
    cost: 20,
    type: "active",
    maxUses: 2,
    icon: "\u{23F8}\u{FE0F}",
    tier: 1,
  },
  {
    id: "hindsight",
    name: "Hindsight",
    description: "After getting one wrong, reveals the answer with explanation",
    cost: 50,
    type: "active",
    maxUses: 1,
    icon: "\u{1F4A1}",
    tier: 3,
  },
  {
    id: "threat_scanner_1",
    name: "Threat Scanner I",
    description: "Subtly highlights suspicious patterns in transcripts",
    cost: 100,
    type: "passive",
    icon: "\u{1F6A8}",
    tier: 1,
  },
  {
    id: "threat_scanner_2",
    name: "Threat Scanner II",
    description: "Highlights more complex attack patterns",
    cost: 250,
    type: "passive",
    icon: "\u{1F6A8}",
    tier: 2,
  },
  {
    id: "xp_boost",
    name: "XP Boost",
    description: "+20% XP from all sources",
    cost: 150,
    type: "passive",
    icon: "\u{2B06}\u{FE0F}",
    tier: 2,
  },
  {
    id: "combo_shield",
    name: "Combo Shield",
    description: "One wrong answer per session doesn't break your combo",
    cost: 200,
    type: "passive",
    icon: "\u{1F6E1}\u{FE0F}",
    tier: 2,
  },
  {
    id: "token_magnet",
    name: "Token Magnet",
    description: "+25% token earnings",
    cost: 175,
    type: "passive",
    icon: "\u{1FA99}",
    tier: 2,
  },
  {
    id: "speed_reader",
    name: "Speed Reader",
    description: "Transcript typewriter animation plays 2x faster",
    cost: 75,
    type: "passive",
    icon: "\u{1F4A8}",
    tier: 1,
  },
  {
    id: "subway_surfer",
    name: "Subway Surfer Mode",
    description: "Adds a brain-rot video sidebar. Makes auditing genuinely harder.",
    cost: 50,
    type: "passive",
    icon: "\u{1F3C4}",
    tier: 1,
  },
  {
    id: "rainbow_mode",
    name: "Rainbow Vomit Mode",
    description: "Cycles all colors through the rainbow. Cursed.",
    cost: 75,
    type: "passive",
    icon: "\u{1F308}",
    tier: 1,
  },
  {
    id: "confetti_cannon",
    name: "Confetti Cannon",
    description: "Burst of confetti on correct answers! (20 particles)",
    cost: 30,
    type: "passive",
    icon: "\u{1F389}",
    tier: 1,
  },
  {
    id: "confetti_cannon_2",
    name: "Confetti Cannon II",
    description: "Upgrade: 100 particles. Pure dopamine.",
    cost: 60,
    type: "passive",
    icon: "\u{1F389}",
    tier: 2,
  },
  {
    id: "confetti_cannon_3",
    name: "Confetti Cannon III",
    description: "Upgrade: 500 particles. Your screen IS confetti.",
    cost: 120,
    type: "passive",
    icon: "\u{1F389}",
    tier: 3,
  },
  {
    id: "speed_lines",
    name: "Anime Speed Lines",
    description: "At combo 5+, anime speed lines appear. At 10+, power aura activates.",
    cost: 40,
    type: "passive",
    icon: "\u{26A1}",
    tier: 1,
  },
  {
    id: "ai_taunts",
    name: "AI Taunts",
    description: "Get roasted by an AI when you get a verdict wrong.",
    cost: 25,
    type: "passive",
    icon: "\u{1F921}",
    tier: 1,
  },
  {
    id: "twitch_chat",
    name: "Twitch Streamer Mode",
    description: "Fake Twitch chat with contextual hints (and trolls). monkaS",
    cost: 60,
    type: "passive",
    icon: "\u{1F4AC}",
    tier: 1,
  },
  {
    id: "screen_shake",
    name: "Screen Shake",
    description: "Shakes the whole screen when you get a verdict wrong. Immersive.",
    cost: 20,
    type: "passive",
    icon: "\u{1F4A5}",
    tier: 1,
  },
  {
    id: "sound_effects",
    name: "Sound Effects",
    description: "Beeps, buzzes, and fanfares for every action. Your coworkers will love it.",
    cost: 10,
    type: "passive",
    icon: "\u{1F50A}",
    tier: 1,
  },
  {
    id: "dancing_anime_girl",
    name: "Dancing Anime Girl",
    description: "A dancing figure in the corner. For moral support.",
    cost: 35,
    type: "passive",
    icon: "\u{1F483}",
    tier: 1,
  },
  {
    id: "mlg_airhorn",
    name: "MLG Air Horn",
    description: "BWAAAMP on every correct answer.",
    cost: 15,
    type: "passive",
    icon: "\u{1F4E3}",
    tier: 1,
  },
  {
    id: "mlg_airhorn_2",
    name: "MLG Air Horn II",
    description: "Adds hit markers and MOM GET THE CAMERA text.",
    cost: 30,
    type: "passive",
    icon: "\u{1F4E3}",
    tier: 2,
  },
  {
    id: "comic_sans",
    name: "Comic Sans Mode",
    description: "Replaces the entire UI font with Comic Sans. The ultimate disrespect.",
    cost: 40,
    type: "passive",
    icon: "\u{1F607}",
    tier: 1,
  },
  {
    id: "dramatic_narrator",
    name: "Dramatic Narrator",
    description: "Reality TV narration captions when you mess up. Cinematic letterboxing included.",
    cost: 35,
    type: "passive",
    icon: "\u{1F3AC}",
    tier: 1,
  },
  {
    id: "jumpscare",
    name: "Jumpscare Mode",
    description: "Miss a malicious transcript? 50% chance of a silly jumpscare. Not sorry.",
    cost: 30,
    type: "passive",
    icon: "\u{1F47B}",
    tier: 1,
  },
  {
    id: "big_head",
    name: "Big Head Mode",
    description: "All emoji become comically massive. The HUD will never be the same.",
    cost: 20,
    type: "passive",
    icon: "\u{1F92F}",
    tier: 1,
  },
  {
    id: "hacker_typer",
    name: "Hacker Typer",
    description: "Movie-style green hacking text scrolls behind the transcript. Very elite.",
    cost: 45,
    type: "passive",
    icon: "\u{1F4BB}",
    tier: 1,
  },
  {
    id: "critical_hit",
    name: "Critical Hit",
    description: "At combo 3+, correct answers can trigger fighting-game damage numbers.",
    cost: 25,
    type: "passive",
    icon: "\u{2694}\u{FE0F}",
    tier: 1,
  },
];

export function getPerkById(id: string): Perk | undefined {
  return PERKS.find((p) => p.id === id);
}
